# Generated by Django 6.0.3 on 2026-03-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticketassignment',
            name='ticket_syst_ticket__0cc4da_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketassignment',
            name='ticket_syst_assigne_c0786b_idx',
        ),
        migrations.RemoveField(
            model_name='ticketcategory',
            name='department',
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_syst_status_7693da_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_syst_priorit_48574e_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_syst_departm_b44b4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_syst_created_3622f6_idx',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.DeleteModel(
            name='TicketAssignment',
        ),
        migrations.DeleteModel(
            name='TicketCategory',
        ),
    ]
