# Generated by Django 6.0.3 on 2026-03-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0006_emailconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailconfig',
            options={'verbose_name': 'Email Configuration', 'verbose_name_plural': 'Email Configurations'},
        ),
        migrations.RenameField(
            model_name='emailconfig',
            old_name='default_from',
            new_name='default_from_email',
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='host',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
