# Generated by Django 6.0.3 on 2026-03-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ticket_system', '0007_alter_emailconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('in_progress_count', models.PositiveIntegerField(default=0)),
                ('resolved_count', models.PositiveIntegerField(default=0)),
                ('closed_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Ticket Report',
                'verbose_name_plural': 'Ticket Reports',
            },
        ),
    ]
