# Generated by Django 6.0.3 on 2026-03-12 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0008_ticketreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketreport',
            options={},
        ),
        migrations.RemoveField(
            model_name='ticketreport',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ticketreport',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticketreport',
            name='closed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketreport',
            name='in_progress_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketreport',
            name='open_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketreport',
            name='resolved_count',
            field=models.IntegerField(default=0),
        ),
    ]
