# Generated by Django 6.0.3 on 2026-03-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0009_alter_ticketreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTickets',
            fields=[
            ],
            options={
                'verbose_name': 'Department Ticket',
                'verbose_name_plural': 'Department Tickets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ticket_system.ticket',),
        ),
        migrations.CreateModel(
            name='MyTickets',
            fields=[
            ],
            options={
                'verbose_name': 'My Ticket',
                'verbose_name_plural': 'My Tickets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ticket_system.ticket',),
        ),
    ]
