# Generated by Django 6.0.3 on 2026-03-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0010_departmenttickets_mytickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='expected_resolution_date',
            field=models.DateTimeField(blank=True, help_text='Expected date/time the department should resolve this ticket', null=True),
        ),
    ]
