# Generated by Django 6.0.3 on 2026-03-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0011_ticket_expected_resolution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
