# Generated by Django 6.0.3 on 2026-05-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0016_postatushistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='POStatusHistory',
        ),
    ]
