# Generated by Django 6.0.3 on 2026-05-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={},
        ),
    ]
