# Generated by Django 6.0.3 on 2026-05-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_alter_purchaseorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at'], 'permissions': [('can_add_po', 'Can add purchase order'), ('can_update_po_status', 'Can update purchase order status')]},
        ),
    ]
