# Generated by Django 6.0.3 on 2026-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0004_alter_purchaseorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
