# Generated by Django 6.0.3 on 2026-05-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0005_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default=1, editable=False, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PurchaseOrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='purchase_orders.purchaseorder')),
            ],
        ),
    ]
